void#closeZout#(#ZipOutputStream#zOut#,#boolean#success#)#throws#IOException#{##if#(#zOut#==#null#)#{##return#;#}##try#{#zOut#.#close#(#)#;#}##catch#(#IOException#ex#)#{##// If we're in this finally clause because of an##// exception, we don't really care if there's an##// exception when closing the stream. E.g. if it##// throws "ZIP file must have at least one entry",##// because an exception happened before we added##// any files, then we must swallow this##// exception. Otherwise, the error that's reported##// will be the close() error, which is not the##// real cause of the problem.##if#(#success#)#{#throw#ex#;#}#}#}