void#testShouldThrowExceptionWhenRpmFails#(#)#throws#Exception#{#Rpm#rpm#=#new#MyRpm#(#)#;#rpm#.#setProject#(#new#org#.#apache#.#tools#.#ant#.#Project#(#)#)#;#rpm#.#setFailOnError#(#true#)#;#// execute#try#{#rpm#.#execute#(#)#;#fail#(#"should have thrown a build exception"#)#;#}#catch#(#BuildException#ex#)#{#assertTrue#(#ex#.#getMessage#(#)#.#indexOf#(#"' failed with exit code 2"#)#!=#-#1#)#;#}#}##void#testShouldNotThrowExceptionWhenRpmFails#(#)#throws#Exception#{#Rpm#rpm#=#new#MyRpm#(#)#;#rpm#.#execute#(#)#;#}##Execute#getExecute#(#Commandline#toExecute#,#ExecuteStreamHandler#streamhandler#)#{#return#new#Execute#(#)#{#public#int#execute#(#)#{#// 2 is != 0 and even, so it is considered#// failure on any platform currently supported#// by Execute#isFailure.#return#2#;#}#}#;#}##int#execute#(#)#{#// 2 is != 0 and even, so it is considered#// failure on any platform currently supported#// by Execute#isFailure.#return#2#;#}##void#log#(#String#msg#,#int#msgLevel#)#{#}##